version: "3.8"

services:
  mysql:
    image: arm64v8/mysql:oracle
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=money_transfer
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=pwd123
    volumes:
      - ./db_data:/var/lib/mysql
      - "./internal/adapters/repository/sqlc/schema/table_user.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./internal/adapters/repository/sqlc/schema/table_account.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
      - money_network
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'

networks:
  money_network:
    driver: bridge