// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package moneytransfer

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg *CreateTransactionParams) (sql.Result, error)
	CreateTransactionEvent(ctx context.Context, arg *CreateTransactionEventParams) error
	DeleteAccountByUserID(ctx context.Context, userID int64) (sql.Result, error)
	GetAccountByID(ctx context.Context, id int64) (*Account, error)
	GetAccountsByUserID(ctx context.Context, userID int64) ([]*Account, error)
	GetTransactionByID(ctx context.Context, id int64) (*Transaction, error)
	GetTransactionByRequestID(ctx context.Context, arg *GetTransactionByRequestIDParams) (*Transaction, error)
	GetUserByUserName(ctx context.Context, userName string) (*User, error)
	InsertAccount(ctx context.Context, arg *InsertAccountParams) (sql.Result, error)
	InsertUser(ctx context.Context, arg *InsertUserParams) (sql.Result, error)
	UpdateTransaction(ctx context.Context, arg *UpdateTransactionParams) error
}

var _ Querier = (*Queries)(nil)
