// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: transaction_event.sql

package moneytransfer

import (
	"context"
	"encoding/json"
)

const createTransactionEvent = `-- name: CreateTransactionEvent :exec
INSERT INTO ` + "`" + `transaction_event` + "`" + ` (` + "`" + `transaction_id` + "`" + `, ` + "`" + `version` + "`" + `, ` + "`" + `data` + "`" + `, ` + "`" + `event_name` + "`" + `)
VALUES (?, ?, ?, ?)
`

type CreateTransactionEventParams struct {
	TransactionID int64           `json:"transaction_id"`
	Version       int32           `json:"version"`
	Data          json.RawMessage `json:"data"`
	EventName     string          `json:"event_name"`
}

func (q *Queries) CreateTransactionEvent(ctx context.Context, arg *CreateTransactionEventParams) error {
	_, err := q.exec(ctx, q.createTransactionEventStmt, createTransactionEvent,
		arg.TransactionID,
		arg.Version,
		arg.Data,
		arg.EventName,
	)
	return err
}
