// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user.sql

package moneytransfer

import (
	"context"
	"database/sql"
)

const insertUser = `-- name: InsertUser :execresult
INSERT INTO user(user_name,
                 password,
                 full_name,
                 phone)
VALUES (?, ?, ?, ?)
`

type InsertUserParams struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
	FullName string `json:"full_name"`
	Phone    string `json:"phone"`
}

func (q *Queries) InsertUser(ctx context.Context, arg *InsertUserParams) (sql.Result, error) {
	return q.exec(ctx, q.insertUserStmt, insertUser,
		arg.UserName,
		arg.Password,
		arg.FullName,
		arg.Phone,
	)
}
