// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: transaction/serivice.proto

package transaction

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MakeDepositRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MakeDepositRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MakeDepositRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MakeDepositRequestMultiError, or nil if none found.
func (m *MakeDepositRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MakeDepositRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() < 1 {
		err := MakeDepositRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAccountId() < 1 {
		err := MakeDepositRequestValidationError{
			field:  "AccountId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRequestId()) < 1 {
		err := MakeDepositRequestValidationError{
			field:  "RequestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := MakeDepositRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCurrency()) < 1 {
		err := MakeDepositRequestValidationError{
			field:  "Currency",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Descriptions

	if len(errors) > 0 {
		return MakeDepositRequestMultiError(errors)
	}

	return nil
}

// MakeDepositRequestMultiError is an error wrapping multiple validation errors
// returned by MakeDepositRequest.ValidateAll() if the designated constraints
// aren't met.
type MakeDepositRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MakeDepositRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MakeDepositRequestMultiError) AllErrors() []error { return m }

// MakeDepositRequestValidationError is the validation error returned by
// MakeDepositRequest.Validate if the designated constraints aren't met.
type MakeDepositRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MakeDepositRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MakeDepositRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MakeDepositRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MakeDepositRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MakeDepositRequestValidationError) ErrorName() string {
	return "MakeDepositRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MakeDepositRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMakeDepositRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MakeDepositRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MakeDepositRequestValidationError{}

// Validate checks the field values on MakeDepositResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MakeDepositResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MakeDepositResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MakeDepositResponseMultiError, or nil if none found.
func (m *MakeDepositResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MakeDepositResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MakeDepositResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MakeDepositResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MakeDepositResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MakeDepositResponseMultiError(errors)
	}

	return nil
}

// MakeDepositResponseMultiError is an error wrapping multiple validation
// errors returned by MakeDepositResponse.ValidateAll() if the designated
// constraints aren't met.
type MakeDepositResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MakeDepositResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MakeDepositResponseMultiError) AllErrors() []error { return m }

// MakeDepositResponseValidationError is the validation error returned by
// MakeDepositResponse.Validate if the designated constraints aren't met.
type MakeDepositResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MakeDepositResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MakeDepositResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MakeDepositResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MakeDepositResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MakeDepositResponseValidationError) ErrorName() string {
	return "MakeDepositResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MakeDepositResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMakeDepositResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MakeDepositResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MakeDepositResponseValidationError{}

// Validate checks the field values on MakeDepositResponse_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MakeDepositResponse_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MakeDepositResponse_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MakeDepositResponse_DataMultiError, or nil if none found.
func (m *MakeDepositResponse_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *MakeDepositResponse_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TransactionId

	// no validation rules for TransactionStatus

	if len(errors) > 0 {
		return MakeDepositResponse_DataMultiError(errors)
	}

	return nil
}

// MakeDepositResponse_DataMultiError is an error wrapping multiple validation
// errors returned by MakeDepositResponse_Data.ValidateAll() if the designated
// constraints aren't met.
type MakeDepositResponse_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MakeDepositResponse_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MakeDepositResponse_DataMultiError) AllErrors() []error { return m }

// MakeDepositResponse_DataValidationError is the validation error returned by
// MakeDepositResponse_Data.Validate if the designated constraints aren't met.
type MakeDepositResponse_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MakeDepositResponse_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MakeDepositResponse_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MakeDepositResponse_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MakeDepositResponse_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MakeDepositResponse_DataValidationError) ErrorName() string {
	return "MakeDepositResponse_DataValidationError"
}

// Error satisfies the builtin error interface
func (e MakeDepositResponse_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMakeDepositResponse_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MakeDepositResponse_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MakeDepositResponse_DataValidationError{}
